version: '3.7'
services:
  postgres:
    image: postgres:13
    container_name: bitmarteshipping
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'db'

volumes:
  postgres:
    name: db
